language: node_js
node_js:
  - 9
cache:
  directories:
  - node_modules
script:
  - npm install
  - npm test
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GH_TOKEN
  local_dir: build
  on:
    branch: master